"use client";

import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { usePhotoDocumentation } from "@/lib/hooks/usePhotoDocumentation";
import { useMoveIn } from "@/components/providers/MoveInProvider";

export function PhotoExportView() {
  const { rooms, useRoomPhotos } = usePhotoDocumentation();
  const { plan } = useMoveIn();

  function handlePrint() {
    window.print();
  }

  if (rooms.length === 0) return null;

  return (
    <>
      {/* Print button (hidden in print) */}
      <div className="print:hidden">
        <Button variant="outline" size="sm" onClick={handlePrint}>
          <Printer className="mr-1.5 h-3.5 w-3.5" />
          Generate report
        </Button>
      </div>

      {/* Printable content (only visible in print) */}
      <div className="hidden print:block">
        <style>{`
          @media print {
            body * { visibility: hidden; }
            .print-report, .print-report * { visibility: visible; }
            .print-report { position: absolute; left: 0; top: 0; width: 100%; }
            .print-photo { break-inside: avoid; }
          }
        `}</style>
        <div className="print-report space-y-8 p-8">
          {/* Header */}
          <div className="space-y-1">
            <h1 className="text-xl font-bold">Move-In Condition Report</h1>
            {plan.targetAddress && (
              <p className="text-sm text-gray-600">{plan.targetAddress}</p>
            )}
            {plan.moveDate && (
              <p className="text-sm text-gray-600">Move-in date: {plan.moveDate}</p>
            )}
            <p className="text-xs text-gray-400">
              Generated {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })} via Wade Me Home
            </p>
          </div>

          {/* Room sections */}
          {rooms.map((room) => (
            <PrintableRoom key={room.id} roomId={room.id} roomLabel={room.roomLabel} />
          ))}

          <p className="text-xs text-gray-400 pt-4 border-t">
            All photos are timestamped at time of capture. GPS coordinates recorded where available.
            This document was generated by Wade Me Home (wademehome.com).
          </p>
        </div>
      </div>
    </>
  );
}

function PrintableRoom({ roomId, roomLabel }: { roomId: string; roomLabel: string }) {
  const { useRoomPhotos } = usePhotoDocumentation();
  const photosQuery = useRoomPhotos(roomId);
  const photos = photosQuery.data ?? [];

  if (photos.length === 0) return null;

  return (
    <div className="space-y-3">
      <h2 className="text-lg font-semibold border-b pb-1">{roomLabel}</h2>
      <div className="grid grid-cols-3 gap-3">
        {photos.map((photo) => (
          <div key={photo.id} className="print-photo space-y-1">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={
                photo.photoUrl.startsWith("http")
                  ? photo.photoUrl
                  : `/api/move-in/photos/file/${photo.photoUrl}`
              }
              alt={photo.note || roomLabel}
              className="w-full rounded border"
            />
            <div className="text-[10px] text-gray-500">
              {photo.capturedAt &&
                new Date(photo.capturedAt).toLocaleString("en-US", {
                  month: "short",
                  day: "numeric",
                  year: "numeric",
                  hour: "numeric",
                  minute: "2-digit",
                })}
              {photo.latitude != null &&
                photo.longitude != null &&
                ` | ${photo.latitude.toFixed(5)}, ${photo.longitude.toFixed(5)}`}
            </div>
            {photo.note && (
              <p className="text-xs text-gray-700">{photo.note}</p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
